/**
 *
 *  AuditLogs.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "AuditLogs.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Gnp;

const std::string AuditLogs::Cols::_id = "\"id\"";
const std::string AuditLogs::Cols::_user_id = "\"user_id\"";
const std::string AuditLogs::Cols::_user_email = "\"user_email\"";
const std::string AuditLogs::Cols::_user_full_name = "\"user_full_name\"";
const std::string AuditLogs::Cols::_action = "\"action\"";
const std::string AuditLogs::Cols::_entity_type = "\"entity_type\"";
const std::string AuditLogs::Cols::_entity_id = "\"entity_id\"";
const std::string AuditLogs::Cols::_old_values = "\"old_values\"";
const std::string AuditLogs::Cols::_new_values = "\"new_values\"";
const std::string AuditLogs::Cols::_ip_address = "\"ip_address\"";
const std::string AuditLogs::Cols::_user_agent = "\"user_agent\"";
const std::string AuditLogs::Cols::_endpoint = "\"endpoint\"";
const std::string AuditLogs::Cols::_http_method = "\"http_method\"";
const std::string AuditLogs::Cols::_http_status_code = "\"http_status_code\"";
const std::string AuditLogs::Cols::_request_id = "\"request_id\"";
const std::string AuditLogs::Cols::_created_at = "\"created_at\"";
const std::string AuditLogs::Cols::_duration_ms = "\"duration_ms\"";
const std::string AuditLogs::Cols::_error_message = "\"error_message\"";
const std::string AuditLogs::Cols::_metadata = "\"metadata\"";
const std::string AuditLogs::primaryKeyName = "id";
const bool AuditLogs::hasPrimaryKey = true;
const std::string AuditLogs::tableName = "\"audit_logs\"";

const std::vector<typename AuditLogs::MetaData> AuditLogs::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"user_id","std::string","character varying",255,0,0,0},
{"user_email","std::string","character varying",255,0,0,0},
{"user_full_name","std::string","character varying",255,0,0,0},
{"action","std::string","character varying",100,0,0,1},
{"entity_type","std::string","character varying",100,0,0,0},
{"entity_id","std::string","character varying",255,0,0,0},
{"old_values","std::string","jsonb",0,0,0,0},
{"new_values","std::string","jsonb",0,0,0,0},
{"ip_address","std::string","inet",0,0,0,0},
{"user_agent","std::string","text",0,0,0,0},
{"endpoint","std::string","character varying",500,0,0,0},
{"http_method","std::string","character varying",10,0,0,0},
{"http_status_code","short","smallint",2,0,0,0},
{"request_id","std::string","uuid",0,0,0,0},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"duration_ms","int32_t","integer",4,0,0,0},
{"error_message","std::string","text",0,0,0,0},
{"metadata","std::string","jsonb",0,0,0,0}
};
const std::string &AuditLogs::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
AuditLogs::AuditLogs(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["user_email"].isNull())
        {
            userEmail_=std::make_shared<std::string>(r["user_email"].as<std::string>());
        }
        if(!r["user_full_name"].isNull())
        {
            userFullName_=std::make_shared<std::string>(r["user_full_name"].as<std::string>());
        }
        if(!r["action"].isNull())
        {
            action_=std::make_shared<std::string>(r["action"].as<std::string>());
        }
        if(!r["entity_type"].isNull())
        {
            entityType_=std::make_shared<std::string>(r["entity_type"].as<std::string>());
        }
        if(!r["entity_id"].isNull())
        {
            entityId_=std::make_shared<std::string>(r["entity_id"].as<std::string>());
        }
        if(!r["old_values"].isNull())
        {
            oldValues_=std::make_shared<std::string>(r["old_values"].as<std::string>());
        }
        if(!r["new_values"].isNull())
        {
            newValues_=std::make_shared<std::string>(r["new_values"].as<std::string>());
        }
        if(!r["ip_address"].isNull())
        {
            ipAddress_=std::make_shared<std::string>(r["ip_address"].as<std::string>());
        }
        if(!r["user_agent"].isNull())
        {
            userAgent_=std::make_shared<std::string>(r["user_agent"].as<std::string>());
        }
        if(!r["endpoint"].isNull())
        {
            endpoint_=std::make_shared<std::string>(r["endpoint"].as<std::string>());
        }
        if(!r["http_method"].isNull())
        {
            httpMethod_=std::make_shared<std::string>(r["http_method"].as<std::string>());
        }
        if(!r["http_status_code"].isNull())
        {
            httpStatusCode_=std::make_shared<short>(r["http_status_code"].as<short>());
        }
        if(!r["request_id"].isNull())
        {
            requestId_=std::make_shared<std::string>(r["request_id"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["duration_ms"].isNull())
        {
            durationMs_=std::make_shared<int32_t>(r["duration_ms"].as<int32_t>());
        }
        if(!r["error_message"].isNull())
        {
            errorMessage_=std::make_shared<std::string>(r["error_message"].as<std::string>());
        }
        if(!r["metadata"].isNull())
        {
            metadata_=std::make_shared<std::string>(r["metadata"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 19 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userEmail_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            userFullName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            action_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            entityType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            entityId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            oldValues_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            newValues_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            ipAddress_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            userAgent_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            endpoint_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            httpMethod_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            httpStatusCode_=std::make_shared<short>(r[index].as<short>());
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            requestId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 15;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 16;
        if(!r[index].isNull())
        {
            durationMs_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 17;
        if(!r[index].isNull())
        {
            errorMessage_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 18;
        if(!r[index].isNull())
        {
            metadata_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

AuditLogs::AuditLogs(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 19)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userEmail_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            userFullName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            action_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            entityType_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            oldValues_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            newValues_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            ipAddress_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            endpoint_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            httpMethod_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            httpStatusCode_=std::make_shared<short>((short)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            requestId_=std::make_shared<std::string>(pJson[pMasqueradingVector[14]].asString());
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[15]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
    {
        dirtyFlag_[16] = true;
        if(!pJson[pMasqueradingVector[16]].isNull())
        {
            durationMs_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[16]].asInt64());
        }
    }
    if(!pMasqueradingVector[17].empty() && pJson.isMember(pMasqueradingVector[17]))
    {
        dirtyFlag_[17] = true;
        if(!pJson[pMasqueradingVector[17]].isNull())
        {
            errorMessage_=std::make_shared<std::string>(pJson[pMasqueradingVector[17]].asString());
        }
    }
    if(!pMasqueradingVector[18].empty() && pJson.isMember(pMasqueradingVector[18]))
    {
        dirtyFlag_[18] = true;
        if(!pJson[pMasqueradingVector[18]].isNull())
        {
            metadata_=std::make_shared<std::string>(pJson[pMasqueradingVector[18]].asString());
        }
    }
}

AuditLogs::AuditLogs(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("user_email"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["user_email"].isNull())
        {
            userEmail_=std::make_shared<std::string>(pJson["user_email"].asString());
        }
    }
    if(pJson.isMember("user_full_name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["user_full_name"].isNull())
        {
            userFullName_=std::make_shared<std::string>(pJson["user_full_name"].asString());
        }
    }
    if(pJson.isMember("action"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["action"].isNull())
        {
            action_=std::make_shared<std::string>(pJson["action"].asString());
        }
    }
    if(pJson.isMember("entity_type"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["entity_type"].isNull())
        {
            entityType_=std::make_shared<std::string>(pJson["entity_type"].asString());
        }
    }
    if(pJson.isMember("entity_id"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["entity_id"].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson["entity_id"].asString());
        }
    }
    if(pJson.isMember("old_values"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["old_values"].isNull())
        {
            oldValues_=std::make_shared<std::string>(pJson["old_values"].asString());
        }
    }
    if(pJson.isMember("new_values"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["new_values"].isNull())
        {
            newValues_=std::make_shared<std::string>(pJson["new_values"].asString());
        }
    }
    if(pJson.isMember("ip_address"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["ip_address"].isNull())
        {
            ipAddress_=std::make_shared<std::string>(pJson["ip_address"].asString());
        }
    }
    if(pJson.isMember("user_agent"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["user_agent"].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson["user_agent"].asString());
        }
    }
    if(pJson.isMember("endpoint"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["endpoint"].isNull())
        {
            endpoint_=std::make_shared<std::string>(pJson["endpoint"].asString());
        }
    }
    if(pJson.isMember("http_method"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["http_method"].isNull())
        {
            httpMethod_=std::make_shared<std::string>(pJson["http_method"].asString());
        }
    }
    if(pJson.isMember("http_status_code"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["http_status_code"].isNull())
        {
            httpStatusCode_=std::make_shared<short>((short)pJson["http_status_code"].asInt64());
        }
    }
    if(pJson.isMember("request_id"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["request_id"].isNull())
        {
            requestId_=std::make_shared<std::string>(pJson["request_id"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[15]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("duration_ms"))
    {
        dirtyFlag_[16]=true;
        if(!pJson["duration_ms"].isNull())
        {
            durationMs_=std::make_shared<int32_t>((int32_t)pJson["duration_ms"].asInt64());
        }
    }
    if(pJson.isMember("error_message"))
    {
        dirtyFlag_[17]=true;
        if(!pJson["error_message"].isNull())
        {
            errorMessage_=std::make_shared<std::string>(pJson["error_message"].asString());
        }
    }
    if(pJson.isMember("metadata"))
    {
        dirtyFlag_[18]=true;
        if(!pJson["metadata"].isNull())
        {
            metadata_=std::make_shared<std::string>(pJson["metadata"].asString());
        }
    }
}

void AuditLogs::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 19)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userEmail_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            userFullName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            action_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            entityType_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            oldValues_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            newValues_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            ipAddress_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            endpoint_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            httpMethod_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            httpStatusCode_=std::make_shared<short>((short)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            requestId_=std::make_shared<std::string>(pJson[pMasqueradingVector[14]].asString());
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[15]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
    {
        dirtyFlag_[16] = true;
        if(!pJson[pMasqueradingVector[16]].isNull())
        {
            durationMs_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[16]].asInt64());
        }
    }
    if(!pMasqueradingVector[17].empty() && pJson.isMember(pMasqueradingVector[17]))
    {
        dirtyFlag_[17] = true;
        if(!pJson[pMasqueradingVector[17]].isNull())
        {
            errorMessage_=std::make_shared<std::string>(pJson[pMasqueradingVector[17]].asString());
        }
    }
    if(!pMasqueradingVector[18].empty() && pJson.isMember(pMasqueradingVector[18]))
    {
        dirtyFlag_[18] = true;
        if(!pJson[pMasqueradingVector[18]].isNull())
        {
            metadata_=std::make_shared<std::string>(pJson[pMasqueradingVector[18]].asString());
        }
    }
}

void AuditLogs::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("user_email"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["user_email"].isNull())
        {
            userEmail_=std::make_shared<std::string>(pJson["user_email"].asString());
        }
    }
    if(pJson.isMember("user_full_name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["user_full_name"].isNull())
        {
            userFullName_=std::make_shared<std::string>(pJson["user_full_name"].asString());
        }
    }
    if(pJson.isMember("action"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["action"].isNull())
        {
            action_=std::make_shared<std::string>(pJson["action"].asString());
        }
    }
    if(pJson.isMember("entity_type"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["entity_type"].isNull())
        {
            entityType_=std::make_shared<std::string>(pJson["entity_type"].asString());
        }
    }
    if(pJson.isMember("entity_id"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["entity_id"].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson["entity_id"].asString());
        }
    }
    if(pJson.isMember("old_values"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["old_values"].isNull())
        {
            oldValues_=std::make_shared<std::string>(pJson["old_values"].asString());
        }
    }
    if(pJson.isMember("new_values"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["new_values"].isNull())
        {
            newValues_=std::make_shared<std::string>(pJson["new_values"].asString());
        }
    }
    if(pJson.isMember("ip_address"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["ip_address"].isNull())
        {
            ipAddress_=std::make_shared<std::string>(pJson["ip_address"].asString());
        }
    }
    if(pJson.isMember("user_agent"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["user_agent"].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson["user_agent"].asString());
        }
    }
    if(pJson.isMember("endpoint"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["endpoint"].isNull())
        {
            endpoint_=std::make_shared<std::string>(pJson["endpoint"].asString());
        }
    }
    if(pJson.isMember("http_method"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["http_method"].isNull())
        {
            httpMethod_=std::make_shared<std::string>(pJson["http_method"].asString());
        }
    }
    if(pJson.isMember("http_status_code"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["http_status_code"].isNull())
        {
            httpStatusCode_=std::make_shared<short>((short)pJson["http_status_code"].asInt64());
        }
    }
    if(pJson.isMember("request_id"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["request_id"].isNull())
        {
            requestId_=std::make_shared<std::string>(pJson["request_id"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[15] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("duration_ms"))
    {
        dirtyFlag_[16] = true;
        if(!pJson["duration_ms"].isNull())
        {
            durationMs_=std::make_shared<int32_t>((int32_t)pJson["duration_ms"].asInt64());
        }
    }
    if(pJson.isMember("error_message"))
    {
        dirtyFlag_[17] = true;
        if(!pJson["error_message"].isNull())
        {
            errorMessage_=std::make_shared<std::string>(pJson["error_message"].asString());
        }
    }
    if(pJson.isMember("metadata"))
    {
        dirtyFlag_[18] = true;
        if(!pJson["metadata"].isNull())
        {
            metadata_=std::make_shared<std::string>(pJson["metadata"].asString());
        }
    }
}

const std::string &AuditLogs::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getId() const noexcept
{
    return id_;
}
void AuditLogs::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void AuditLogs::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename AuditLogs::PrimaryKeyType & AuditLogs::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &AuditLogs::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getUserId() const noexcept
{
    return userId_;
}
void AuditLogs::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[1] = true;
}
void AuditLogs::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[1] = true;
}
void AuditLogs::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &AuditLogs::getValueOfUserEmail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userEmail_)
        return *userEmail_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getUserEmail() const noexcept
{
    return userEmail_;
}
void AuditLogs::setUserEmail(const std::string &pUserEmail) noexcept
{
    userEmail_ = std::make_shared<std::string>(pUserEmail);
    dirtyFlag_[2] = true;
}
void AuditLogs::setUserEmail(std::string &&pUserEmail) noexcept
{
    userEmail_ = std::make_shared<std::string>(std::move(pUserEmail));
    dirtyFlag_[2] = true;
}
void AuditLogs::setUserEmailToNull() noexcept
{
    userEmail_.reset();
    dirtyFlag_[2] = true;
}

const std::string &AuditLogs::getValueOfUserFullName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userFullName_)
        return *userFullName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getUserFullName() const noexcept
{
    return userFullName_;
}
void AuditLogs::setUserFullName(const std::string &pUserFullName) noexcept
{
    userFullName_ = std::make_shared<std::string>(pUserFullName);
    dirtyFlag_[3] = true;
}
void AuditLogs::setUserFullName(std::string &&pUserFullName) noexcept
{
    userFullName_ = std::make_shared<std::string>(std::move(pUserFullName));
    dirtyFlag_[3] = true;
}
void AuditLogs::setUserFullNameToNull() noexcept
{
    userFullName_.reset();
    dirtyFlag_[3] = true;
}

const std::string &AuditLogs::getValueOfAction() const noexcept
{
    static const std::string defaultValue = std::string();
    if(action_)
        return *action_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getAction() const noexcept
{
    return action_;
}
void AuditLogs::setAction(const std::string &pAction) noexcept
{
    action_ = std::make_shared<std::string>(pAction);
    dirtyFlag_[4] = true;
}
void AuditLogs::setAction(std::string &&pAction) noexcept
{
    action_ = std::make_shared<std::string>(std::move(pAction));
    dirtyFlag_[4] = true;
}

const std::string &AuditLogs::getValueOfEntityType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(entityType_)
        return *entityType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getEntityType() const noexcept
{
    return entityType_;
}
void AuditLogs::setEntityType(const std::string &pEntityType) noexcept
{
    entityType_ = std::make_shared<std::string>(pEntityType);
    dirtyFlag_[5] = true;
}
void AuditLogs::setEntityType(std::string &&pEntityType) noexcept
{
    entityType_ = std::make_shared<std::string>(std::move(pEntityType));
    dirtyFlag_[5] = true;
}
void AuditLogs::setEntityTypeToNull() noexcept
{
    entityType_.reset();
    dirtyFlag_[5] = true;
}

const std::string &AuditLogs::getValueOfEntityId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(entityId_)
        return *entityId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getEntityId() const noexcept
{
    return entityId_;
}
void AuditLogs::setEntityId(const std::string &pEntityId) noexcept
{
    entityId_ = std::make_shared<std::string>(pEntityId);
    dirtyFlag_[6] = true;
}
void AuditLogs::setEntityId(std::string &&pEntityId) noexcept
{
    entityId_ = std::make_shared<std::string>(std::move(pEntityId));
    dirtyFlag_[6] = true;
}
void AuditLogs::setEntityIdToNull() noexcept
{
    entityId_.reset();
    dirtyFlag_[6] = true;
}

const std::string &AuditLogs::getValueOfOldValues() const noexcept
{
    static const std::string defaultValue = std::string();
    if(oldValues_)
        return *oldValues_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getOldValues() const noexcept
{
    return oldValues_;
}
void AuditLogs::setOldValues(const std::string &pOldValues) noexcept
{
    oldValues_ = std::make_shared<std::string>(pOldValues);
    dirtyFlag_[7] = true;
}
void AuditLogs::setOldValues(std::string &&pOldValues) noexcept
{
    oldValues_ = std::make_shared<std::string>(std::move(pOldValues));
    dirtyFlag_[7] = true;
}
void AuditLogs::setOldValuesToNull() noexcept
{
    oldValues_.reset();
    dirtyFlag_[7] = true;
}

const std::string &AuditLogs::getValueOfNewValues() const noexcept
{
    static const std::string defaultValue = std::string();
    if(newValues_)
        return *newValues_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getNewValues() const noexcept
{
    return newValues_;
}
void AuditLogs::setNewValues(const std::string &pNewValues) noexcept
{
    newValues_ = std::make_shared<std::string>(pNewValues);
    dirtyFlag_[8] = true;
}
void AuditLogs::setNewValues(std::string &&pNewValues) noexcept
{
    newValues_ = std::make_shared<std::string>(std::move(pNewValues));
    dirtyFlag_[8] = true;
}
void AuditLogs::setNewValuesToNull() noexcept
{
    newValues_.reset();
    dirtyFlag_[8] = true;
}

const std::string &AuditLogs::getValueOfIpAddress() const noexcept
{
    static const std::string defaultValue = std::string();
    if(ipAddress_)
        return *ipAddress_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getIpAddress() const noexcept
{
    return ipAddress_;
}
void AuditLogs::setIpAddress(const std::string &pIpAddress) noexcept
{
    ipAddress_ = std::make_shared<std::string>(pIpAddress);
    dirtyFlag_[9] = true;
}
void AuditLogs::setIpAddress(std::string &&pIpAddress) noexcept
{
    ipAddress_ = std::make_shared<std::string>(std::move(pIpAddress));
    dirtyFlag_[9] = true;
}
void AuditLogs::setIpAddressToNull() noexcept
{
    ipAddress_.reset();
    dirtyFlag_[9] = true;
}

const std::string &AuditLogs::getValueOfUserAgent() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userAgent_)
        return *userAgent_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getUserAgent() const noexcept
{
    return userAgent_;
}
void AuditLogs::setUserAgent(const std::string &pUserAgent) noexcept
{
    userAgent_ = std::make_shared<std::string>(pUserAgent);
    dirtyFlag_[10] = true;
}
void AuditLogs::setUserAgent(std::string &&pUserAgent) noexcept
{
    userAgent_ = std::make_shared<std::string>(std::move(pUserAgent));
    dirtyFlag_[10] = true;
}
void AuditLogs::setUserAgentToNull() noexcept
{
    userAgent_.reset();
    dirtyFlag_[10] = true;
}

const std::string &AuditLogs::getValueOfEndpoint() const noexcept
{
    static const std::string defaultValue = std::string();
    if(endpoint_)
        return *endpoint_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getEndpoint() const noexcept
{
    return endpoint_;
}
void AuditLogs::setEndpoint(const std::string &pEndpoint) noexcept
{
    endpoint_ = std::make_shared<std::string>(pEndpoint);
    dirtyFlag_[11] = true;
}
void AuditLogs::setEndpoint(std::string &&pEndpoint) noexcept
{
    endpoint_ = std::make_shared<std::string>(std::move(pEndpoint));
    dirtyFlag_[11] = true;
}
void AuditLogs::setEndpointToNull() noexcept
{
    endpoint_.reset();
    dirtyFlag_[11] = true;
}

const std::string &AuditLogs::getValueOfHttpMethod() const noexcept
{
    static const std::string defaultValue = std::string();
    if(httpMethod_)
        return *httpMethod_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getHttpMethod() const noexcept
{
    return httpMethod_;
}
void AuditLogs::setHttpMethod(const std::string &pHttpMethod) noexcept
{
    httpMethod_ = std::make_shared<std::string>(pHttpMethod);
    dirtyFlag_[12] = true;
}
void AuditLogs::setHttpMethod(std::string &&pHttpMethod) noexcept
{
    httpMethod_ = std::make_shared<std::string>(std::move(pHttpMethod));
    dirtyFlag_[12] = true;
}
void AuditLogs::setHttpMethodToNull() noexcept
{
    httpMethod_.reset();
    dirtyFlag_[12] = true;
}

const short &AuditLogs::getValueOfHttpStatusCode() const noexcept
{
    static const short defaultValue = short();
    if(httpStatusCode_)
        return *httpStatusCode_;
    return defaultValue;
}
const std::shared_ptr<short> &AuditLogs::getHttpStatusCode() const noexcept
{
    return httpStatusCode_;
}
void AuditLogs::setHttpStatusCode(const short &pHttpStatusCode) noexcept
{
    httpStatusCode_ = std::make_shared<short>(pHttpStatusCode);
    dirtyFlag_[13] = true;
}
void AuditLogs::setHttpStatusCodeToNull() noexcept
{
    httpStatusCode_.reset();
    dirtyFlag_[13] = true;
}

const std::string &AuditLogs::getValueOfRequestId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(requestId_)
        return *requestId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getRequestId() const noexcept
{
    return requestId_;
}
void AuditLogs::setRequestId(const std::string &pRequestId) noexcept
{
    requestId_ = std::make_shared<std::string>(pRequestId);
    dirtyFlag_[14] = true;
}
void AuditLogs::setRequestId(std::string &&pRequestId) noexcept
{
    requestId_ = std::make_shared<std::string>(std::move(pRequestId));
    dirtyFlag_[14] = true;
}
void AuditLogs::setRequestIdToNull() noexcept
{
    requestId_.reset();
    dirtyFlag_[14] = true;
}

const ::trantor::Date &AuditLogs::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &AuditLogs::getCreatedAt() const noexcept
{
    return createdAt_;
}
void AuditLogs::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[15] = true;
}

const int32_t &AuditLogs::getValueOfDurationMs() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(durationMs_)
        return *durationMs_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &AuditLogs::getDurationMs() const noexcept
{
    return durationMs_;
}
void AuditLogs::setDurationMs(const int32_t &pDurationMs) noexcept
{
    durationMs_ = std::make_shared<int32_t>(pDurationMs);
    dirtyFlag_[16] = true;
}
void AuditLogs::setDurationMsToNull() noexcept
{
    durationMs_.reset();
    dirtyFlag_[16] = true;
}

const std::string &AuditLogs::getValueOfErrorMessage() const noexcept
{
    static const std::string defaultValue = std::string();
    if(errorMessage_)
        return *errorMessage_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getErrorMessage() const noexcept
{
    return errorMessage_;
}
void AuditLogs::setErrorMessage(const std::string &pErrorMessage) noexcept
{
    errorMessage_ = std::make_shared<std::string>(pErrorMessage);
    dirtyFlag_[17] = true;
}
void AuditLogs::setErrorMessage(std::string &&pErrorMessage) noexcept
{
    errorMessage_ = std::make_shared<std::string>(std::move(pErrorMessage));
    dirtyFlag_[17] = true;
}
void AuditLogs::setErrorMessageToNull() noexcept
{
    errorMessage_.reset();
    dirtyFlag_[17] = true;
}

const std::string &AuditLogs::getValueOfMetadata() const noexcept
{
    static const std::string defaultValue = std::string();
    if(metadata_)
        return *metadata_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getMetadata() const noexcept
{
    return metadata_;
}
void AuditLogs::setMetadata(const std::string &pMetadata) noexcept
{
    metadata_ = std::make_shared<std::string>(pMetadata);
    dirtyFlag_[18] = true;
}
void AuditLogs::setMetadata(std::string &&pMetadata) noexcept
{
    metadata_ = std::make_shared<std::string>(std::move(pMetadata));
    dirtyFlag_[18] = true;
}
void AuditLogs::setMetadataToNull() noexcept
{
    metadata_.reset();
    dirtyFlag_[18] = true;
}

void AuditLogs::updateId(const uint64_t id)
{
}

const std::vector<std::string> &AuditLogs::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "user_id",
        "user_email",
        "user_full_name",
        "action",
        "entity_type",
        "entity_id",
        "old_values",
        "new_values",
        "ip_address",
        "user_agent",
        "endpoint",
        "http_method",
        "http_status_code",
        "request_id",
        "created_at",
        "duration_ms",
        "error_message",
        "metadata"
    };
    return inCols;
}

void AuditLogs::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserEmail())
        {
            binder << getValueOfUserEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getUserFullName())
        {
            binder << getValueOfUserFullName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAction())
        {
            binder << getValueOfAction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEntityType())
        {
            binder << getValueOfEntityType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getEntityId())
        {
            binder << getValueOfEntityId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getOldValues())
        {
            binder << getValueOfOldValues();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getNewValues())
        {
            binder << getValueOfNewValues();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getIpAddress())
        {
            binder << getValueOfIpAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getUserAgent())
        {
            binder << getValueOfUserAgent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getEndpoint())
        {
            binder << getValueOfEndpoint();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getHttpMethod())
        {
            binder << getValueOfHttpMethod();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getHttpStatusCode())
        {
            binder << getValueOfHttpStatusCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getRequestId())
        {
            binder << getValueOfRequestId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[16])
    {
        if(getDurationMs())
        {
            binder << getValueOfDurationMs();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[17])
    {
        if(getErrorMessage())
        {
            binder << getValueOfErrorMessage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[18])
    {
        if(getMetadata())
        {
            binder << getValueOfMetadata();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> AuditLogs::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    if(dirtyFlag_[15])
    {
        ret.push_back(getColumnName(15));
    }
    if(dirtyFlag_[16])
    {
        ret.push_back(getColumnName(16));
    }
    if(dirtyFlag_[17])
    {
        ret.push_back(getColumnName(17));
    }
    if(dirtyFlag_[18])
    {
        ret.push_back(getColumnName(18));
    }
    return ret;
}

void AuditLogs::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserEmail())
        {
            binder << getValueOfUserEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getUserFullName())
        {
            binder << getValueOfUserFullName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAction())
        {
            binder << getValueOfAction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEntityType())
        {
            binder << getValueOfEntityType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getEntityId())
        {
            binder << getValueOfEntityId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getOldValues())
        {
            binder << getValueOfOldValues();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getNewValues())
        {
            binder << getValueOfNewValues();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getIpAddress())
        {
            binder << getValueOfIpAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getUserAgent())
        {
            binder << getValueOfUserAgent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getEndpoint())
        {
            binder << getValueOfEndpoint();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getHttpMethod())
        {
            binder << getValueOfHttpMethod();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getHttpStatusCode())
        {
            binder << getValueOfHttpStatusCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getRequestId())
        {
            binder << getValueOfRequestId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[16])
    {
        if(getDurationMs())
        {
            binder << getValueOfDurationMs();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[17])
    {
        if(getErrorMessage())
        {
            binder << getValueOfErrorMessage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[18])
    {
        if(getMetadata())
        {
            binder << getValueOfMetadata();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value AuditLogs::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getUserEmail())
    {
        ret["user_email"]=getValueOfUserEmail();
    }
    else
    {
        ret["user_email"]=Json::Value();
    }
    if(getUserFullName())
    {
        ret["user_full_name"]=getValueOfUserFullName();
    }
    else
    {
        ret["user_full_name"]=Json::Value();
    }
    if(getAction())
    {
        ret["action"]=getValueOfAction();
    }
    else
    {
        ret["action"]=Json::Value();
    }
    if(getEntityType())
    {
        ret["entity_type"]=getValueOfEntityType();
    }
    else
    {
        ret["entity_type"]=Json::Value();
    }
    if(getEntityId())
    {
        ret["entity_id"]=getValueOfEntityId();
    }
    else
    {
        ret["entity_id"]=Json::Value();
    }
    if(getOldValues())
    {
        ret["old_values"]=getValueOfOldValues();
    }
    else
    {
        ret["old_values"]=Json::Value();
    }
    if(getNewValues())
    {
        ret["new_values"]=getValueOfNewValues();
    }
    else
    {
        ret["new_values"]=Json::Value();
    }
    if(getIpAddress())
    {
        ret["ip_address"]=getValueOfIpAddress();
    }
    else
    {
        ret["ip_address"]=Json::Value();
    }
    if(getUserAgent())
    {
        ret["user_agent"]=getValueOfUserAgent();
    }
    else
    {
        ret["user_agent"]=Json::Value();
    }
    if(getEndpoint())
    {
        ret["endpoint"]=getValueOfEndpoint();
    }
    else
    {
        ret["endpoint"]=Json::Value();
    }
    if(getHttpMethod())
    {
        ret["http_method"]=getValueOfHttpMethod();
    }
    else
    {
        ret["http_method"]=Json::Value();
    }
    if(getHttpStatusCode())
    {
        ret["http_status_code"]=getValueOfHttpStatusCode();
    }
    else
    {
        ret["http_status_code"]=Json::Value();
    }
    if(getRequestId())
    {
        ret["request_id"]=getValueOfRequestId();
    }
    else
    {
        ret["request_id"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getDurationMs())
    {
        ret["duration_ms"]=getValueOfDurationMs();
    }
    else
    {
        ret["duration_ms"]=Json::Value();
    }
    if(getErrorMessage())
    {
        ret["error_message"]=getValueOfErrorMessage();
    }
    else
    {
        ret["error_message"]=Json::Value();
    }
    if(getMetadata())
    {
        ret["metadata"]=getValueOfMetadata();
    }
    else
    {
        ret["metadata"]=Json::Value();
    }
    return ret;
}

std::string AuditLogs::toString() const
{
    return toJson().toStyledString();
}

Json::Value AuditLogs::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 19)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserEmail())
            {
                ret[pMasqueradingVector[2]]=getValueOfUserEmail();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getUserFullName())
            {
                ret[pMasqueradingVector[3]]=getValueOfUserFullName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getAction())
            {
                ret[pMasqueradingVector[4]]=getValueOfAction();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getEntityType())
            {
                ret[pMasqueradingVector[5]]=getValueOfEntityType();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getEntityId())
            {
                ret[pMasqueradingVector[6]]=getValueOfEntityId();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getOldValues())
            {
                ret[pMasqueradingVector[7]]=getValueOfOldValues();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getNewValues())
            {
                ret[pMasqueradingVector[8]]=getValueOfNewValues();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getIpAddress())
            {
                ret[pMasqueradingVector[9]]=getValueOfIpAddress();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getUserAgent())
            {
                ret[pMasqueradingVector[10]]=getValueOfUserAgent();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getEndpoint())
            {
                ret[pMasqueradingVector[11]]=getValueOfEndpoint();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getHttpMethod())
            {
                ret[pMasqueradingVector[12]]=getValueOfHttpMethod();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getHttpStatusCode())
            {
                ret[pMasqueradingVector[13]]=getValueOfHttpStatusCode();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getRequestId())
            {
                ret[pMasqueradingVector[14]]=getValueOfRequestId();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[15].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[15]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[15]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[16].empty())
        {
            if(getDurationMs())
            {
                ret[pMasqueradingVector[16]]=getValueOfDurationMs();
            }
            else
            {
                ret[pMasqueradingVector[16]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[17].empty())
        {
            if(getErrorMessage())
            {
                ret[pMasqueradingVector[17]]=getValueOfErrorMessage();
            }
            else
            {
                ret[pMasqueradingVector[17]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[18].empty())
        {
            if(getMetadata())
            {
                ret[pMasqueradingVector[18]]=getValueOfMetadata();
            }
            else
            {
                ret[pMasqueradingVector[18]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getUserEmail())
    {
        ret["user_email"]=getValueOfUserEmail();
    }
    else
    {
        ret["user_email"]=Json::Value();
    }
    if(getUserFullName())
    {
        ret["user_full_name"]=getValueOfUserFullName();
    }
    else
    {
        ret["user_full_name"]=Json::Value();
    }
    if(getAction())
    {
        ret["action"]=getValueOfAction();
    }
    else
    {
        ret["action"]=Json::Value();
    }
    if(getEntityType())
    {
        ret["entity_type"]=getValueOfEntityType();
    }
    else
    {
        ret["entity_type"]=Json::Value();
    }
    if(getEntityId())
    {
        ret["entity_id"]=getValueOfEntityId();
    }
    else
    {
        ret["entity_id"]=Json::Value();
    }
    if(getOldValues())
    {
        ret["old_values"]=getValueOfOldValues();
    }
    else
    {
        ret["old_values"]=Json::Value();
    }
    if(getNewValues())
    {
        ret["new_values"]=getValueOfNewValues();
    }
    else
    {
        ret["new_values"]=Json::Value();
    }
    if(getIpAddress())
    {
        ret["ip_address"]=getValueOfIpAddress();
    }
    else
    {
        ret["ip_address"]=Json::Value();
    }
    if(getUserAgent())
    {
        ret["user_agent"]=getValueOfUserAgent();
    }
    else
    {
        ret["user_agent"]=Json::Value();
    }
    if(getEndpoint())
    {
        ret["endpoint"]=getValueOfEndpoint();
    }
    else
    {
        ret["endpoint"]=Json::Value();
    }
    if(getHttpMethod())
    {
        ret["http_method"]=getValueOfHttpMethod();
    }
    else
    {
        ret["http_method"]=Json::Value();
    }
    if(getHttpStatusCode())
    {
        ret["http_status_code"]=getValueOfHttpStatusCode();
    }
    else
    {
        ret["http_status_code"]=Json::Value();
    }
    if(getRequestId())
    {
        ret["request_id"]=getValueOfRequestId();
    }
    else
    {
        ret["request_id"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getDurationMs())
    {
        ret["duration_ms"]=getValueOfDurationMs();
    }
    else
    {
        ret["duration_ms"]=Json::Value();
    }
    if(getErrorMessage())
    {
        ret["error_message"]=getValueOfErrorMessage();
    }
    else
    {
        ret["error_message"]=Json::Value();
    }
    if(getMetadata())
    {
        ret["metadata"]=getValueOfMetadata();
    }
    else
    {
        ret["metadata"]=Json::Value();
    }
    return ret;
}

bool AuditLogs::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("user_email"))
    {
        if(!validJsonOfField(2, "user_email", pJson["user_email"], err, true))
            return false;
    }
    if(pJson.isMember("user_full_name"))
    {
        if(!validJsonOfField(3, "user_full_name", pJson["user_full_name"], err, true))
            return false;
    }
    if(pJson.isMember("action"))
    {
        if(!validJsonOfField(4, "action", pJson["action"], err, true))
            return false;
    }
    else
    {
        err="The action column cannot be null";
        return false;
    }
    if(pJson.isMember("entity_type"))
    {
        if(!validJsonOfField(5, "entity_type", pJson["entity_type"], err, true))
            return false;
    }
    if(pJson.isMember("entity_id"))
    {
        if(!validJsonOfField(6, "entity_id", pJson["entity_id"], err, true))
            return false;
    }
    if(pJson.isMember("old_values"))
    {
        if(!validJsonOfField(7, "old_values", pJson["old_values"], err, true))
            return false;
    }
    if(pJson.isMember("new_values"))
    {
        if(!validJsonOfField(8, "new_values", pJson["new_values"], err, true))
            return false;
    }
    if(pJson.isMember("ip_address"))
    {
        if(!validJsonOfField(9, "ip_address", pJson["ip_address"], err, true))
            return false;
    }
    if(pJson.isMember("user_agent"))
    {
        if(!validJsonOfField(10, "user_agent", pJson["user_agent"], err, true))
            return false;
    }
    if(pJson.isMember("endpoint"))
    {
        if(!validJsonOfField(11, "endpoint", pJson["endpoint"], err, true))
            return false;
    }
    if(pJson.isMember("http_method"))
    {
        if(!validJsonOfField(12, "http_method", pJson["http_method"], err, true))
            return false;
    }
    if(pJson.isMember("http_status_code"))
    {
        if(!validJsonOfField(13, "http_status_code", pJson["http_status_code"], err, true))
            return false;
    }
    if(pJson.isMember("request_id"))
    {
        if(!validJsonOfField(14, "request_id", pJson["request_id"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(15, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("duration_ms"))
    {
        if(!validJsonOfField(16, "duration_ms", pJson["duration_ms"], err, true))
            return false;
    }
    if(pJson.isMember("error_message"))
    {
        if(!validJsonOfField(17, "error_message", pJson["error_message"], err, true))
            return false;
    }
    if(pJson.isMember("metadata"))
    {
        if(!validJsonOfField(18, "metadata", pJson["metadata"], err, true))
            return false;
    }
    return true;
}
bool AuditLogs::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 19)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[15].empty())
      {
          if(pJson.isMember(pMasqueradingVector[15]))
          {
              if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[16].empty())
      {
          if(pJson.isMember(pMasqueradingVector[16]))
          {
              if(!validJsonOfField(16, pMasqueradingVector[16], pJson[pMasqueradingVector[16]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[17].empty())
      {
          if(pJson.isMember(pMasqueradingVector[17]))
          {
              if(!validJsonOfField(17, pMasqueradingVector[17], pJson[pMasqueradingVector[17]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[18].empty())
      {
          if(pJson.isMember(pMasqueradingVector[18]))
          {
              if(!validJsonOfField(18, pMasqueradingVector[18], pJson[pMasqueradingVector[18]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AuditLogs::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("user_email"))
    {
        if(!validJsonOfField(2, "user_email", pJson["user_email"], err, false))
            return false;
    }
    if(pJson.isMember("user_full_name"))
    {
        if(!validJsonOfField(3, "user_full_name", pJson["user_full_name"], err, false))
            return false;
    }
    if(pJson.isMember("action"))
    {
        if(!validJsonOfField(4, "action", pJson["action"], err, false))
            return false;
    }
    if(pJson.isMember("entity_type"))
    {
        if(!validJsonOfField(5, "entity_type", pJson["entity_type"], err, false))
            return false;
    }
    if(pJson.isMember("entity_id"))
    {
        if(!validJsonOfField(6, "entity_id", pJson["entity_id"], err, false))
            return false;
    }
    if(pJson.isMember("old_values"))
    {
        if(!validJsonOfField(7, "old_values", pJson["old_values"], err, false))
            return false;
    }
    if(pJson.isMember("new_values"))
    {
        if(!validJsonOfField(8, "new_values", pJson["new_values"], err, false))
            return false;
    }
    if(pJson.isMember("ip_address"))
    {
        if(!validJsonOfField(9, "ip_address", pJson["ip_address"], err, false))
            return false;
    }
    if(pJson.isMember("user_agent"))
    {
        if(!validJsonOfField(10, "user_agent", pJson["user_agent"], err, false))
            return false;
    }
    if(pJson.isMember("endpoint"))
    {
        if(!validJsonOfField(11, "endpoint", pJson["endpoint"], err, false))
            return false;
    }
    if(pJson.isMember("http_method"))
    {
        if(!validJsonOfField(12, "http_method", pJson["http_method"], err, false))
            return false;
    }
    if(pJson.isMember("http_status_code"))
    {
        if(!validJsonOfField(13, "http_status_code", pJson["http_status_code"], err, false))
            return false;
    }
    if(pJson.isMember("request_id"))
    {
        if(!validJsonOfField(14, "request_id", pJson["request_id"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(15, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("duration_ms"))
    {
        if(!validJsonOfField(16, "duration_ms", pJson["duration_ms"], err, false))
            return false;
    }
    if(pJson.isMember("error_message"))
    {
        if(!validJsonOfField(17, "error_message", pJson["error_message"], err, false))
            return false;
    }
    if(pJson.isMember("metadata"))
    {
        if(!validJsonOfField(18, "metadata", pJson["metadata"], err, false))
            return false;
    }
    return true;
}
bool AuditLogs::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 19)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
      if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
      {
          if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, false))
              return false;
      }
      if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
      {
          if(!validJsonOfField(16, pMasqueradingVector[16], pJson[pMasqueradingVector[16]], err, false))
              return false;
      }
      if(!pMasqueradingVector[17].empty() && pJson.isMember(pMasqueradingVector[17]))
      {
          if(!validJsonOfField(17, pMasqueradingVector[17], pJson[pMasqueradingVector[17]], err, false))
              return false;
      }
      if(!pMasqueradingVector[18].empty() && pJson.isMember(pMasqueradingVector[18]))
      {
          if(!validJsonOfField(18, pMasqueradingVector[18], pJson[pMasqueradingVector[18]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AuditLogs::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 500)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 500)";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 10)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 10)";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 15:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 16:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 17:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 18:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
