/**
 *
 *  Campaigns.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Campaigns.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Gnp;

const std::string Campaigns::Cols::_id = "\"id\"";
const std::string Campaigns::Cols::_name = "\"name\"";
const std::string Campaigns::Cols::_deep_link = "\"deep_link\"";
const std::string Campaigns::Cols::_target_audience = "\"target_audience\"";
const std::string Campaigns::Cols::_channel = "\"channel\"";
const std::string Campaigns::Cols::_subject = "\"subject\"";
const std::string Campaigns::Cols::_message_body = "\"message_body\"";
const std::string Campaigns::Cols::_status = "\"status\"";
const std::string Campaigns::Cols::_scheduled_time = "\"scheduled_time\"";
const std::string Campaigns::Cols::_campaign_type = "\"campaign_type\"";
const std::string Campaigns::Cols::_reach = "\"reach\"";
const std::string Campaigns::Cols::_clicks = "\"clicks\"";
const std::string Campaigns::Cols::_created_at = "\"created_at\"";
const std::string Campaigns::Cols::_updated_at = "\"updated_at\"";
const std::string Campaigns::Cols::_html_template = "\"html_template\"";
const std::string Campaigns::primaryKeyName = "id";
const bool Campaigns::hasPrimaryKey = true;
const std::string Campaigns::tableName = "\"campaigns\"";

const std::vector<typename Campaigns::MetaData> Campaigns::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"name","std::string","character varying",255,0,0,1},
{"deep_link","std::string","character varying",350,0,0,0},
{"target_audience","std::string","character varying",50,0,0,1},
{"channel","std::string","character varying",50,0,0,1},
{"subject","std::string","character varying",150,0,0,1},
{"message_body","std::string","character varying",255,0,0,1},
{"status","std::string","character varying",50,0,0,1},
{"scheduled_time","::trantor::Date","timestamp without time zone",0,0,0,0},
{"campaign_type","std::string","character varying",50,0,0,1},
{"reach","int32_t","integer",4,0,0,0},
{"clicks","int32_t","integer",4,0,0,0},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"updated_at","::trantor::Date","timestamp without time zone",0,0,0,0},
{"html_template","std::string","text",0,0,0,0}
};
const std::string &Campaigns::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Campaigns::Campaigns(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["deep_link"].isNull())
        {
            deepLink_=std::make_shared<std::string>(r["deep_link"].as<std::string>());
        }
        if(!r["target_audience"].isNull())
        {
            targetAudience_=std::make_shared<std::string>(r["target_audience"].as<std::string>());
        }
        if(!r["channel"].isNull())
        {
            channel_=std::make_shared<std::string>(r["channel"].as<std::string>());
        }
        if(!r["subject"].isNull())
        {
            subject_=std::make_shared<std::string>(r["subject"].as<std::string>());
        }
        if(!r["message_body"].isNull())
        {
            messageBody_=std::make_shared<std::string>(r["message_body"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["scheduled_time"].isNull())
        {
            auto timeStr = r["scheduled_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                scheduledTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["campaign_type"].isNull())
        {
            campaignType_=std::make_shared<std::string>(r["campaign_type"].as<std::string>());
        }
        if(!r["reach"].isNull())
        {
            reach_=std::make_shared<int32_t>(r["reach"].as<int32_t>());
        }
        if(!r["clicks"].isNull())
        {
            clicks_=std::make_shared<int32_t>(r["clicks"].as<int32_t>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["html_template"].isNull())
        {
            htmlTemplate_=std::make_shared<std::string>(r["html_template"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 15 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            deepLink_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            targetAudience_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            channel_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            subject_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            messageBody_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                scheduledTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            campaignType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            reach_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            clicks_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            htmlTemplate_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Campaigns::Campaigns(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            deepLink_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            targetAudience_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            channel_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            subject_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            messageBody_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                scheduledTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            campaignType_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            reach_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            clicks_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[11]].asInt64());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            htmlTemplate_=std::make_shared<std::string>(pJson[pMasqueradingVector[14]].asString());
        }
    }
}

Campaigns::Campaigns(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("deep_link"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["deep_link"].isNull())
        {
            deepLink_=std::make_shared<std::string>(pJson["deep_link"].asString());
        }
    }
    if(pJson.isMember("target_audience"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["target_audience"].isNull())
        {
            targetAudience_=std::make_shared<std::string>(pJson["target_audience"].asString());
        }
    }
    if(pJson.isMember("channel"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["channel"].isNull())
        {
            channel_=std::make_shared<std::string>(pJson["channel"].asString());
        }
    }
    if(pJson.isMember("subject"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["subject"].isNull())
        {
            subject_=std::make_shared<std::string>(pJson["subject"].asString());
        }
    }
    if(pJson.isMember("message_body"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["message_body"].isNull())
        {
            messageBody_=std::make_shared<std::string>(pJson["message_body"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("scheduled_time"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["scheduled_time"].isNull())
        {
            auto timeStr = pJson["scheduled_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                scheduledTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("campaign_type"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["campaign_type"].isNull())
        {
            campaignType_=std::make_shared<std::string>(pJson["campaign_type"].asString());
        }
    }
    if(pJson.isMember("reach"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["reach"].isNull())
        {
            reach_=std::make_shared<int32_t>((int32_t)pJson["reach"].asInt64());
        }
    }
    if(pJson.isMember("clicks"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["clicks"].isNull())
        {
            clicks_=std::make_shared<int32_t>((int32_t)pJson["clicks"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("html_template"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["html_template"].isNull())
        {
            htmlTemplate_=std::make_shared<std::string>(pJson["html_template"].asString());
        }
    }
}

void Campaigns::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            deepLink_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            targetAudience_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            channel_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            subject_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            messageBody_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                scheduledTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            campaignType_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            reach_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            clicks_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[11]].asInt64());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            htmlTemplate_=std::make_shared<std::string>(pJson[pMasqueradingVector[14]].asString());
        }
    }
}

void Campaigns::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("deep_link"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["deep_link"].isNull())
        {
            deepLink_=std::make_shared<std::string>(pJson["deep_link"].asString());
        }
    }
    if(pJson.isMember("target_audience"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["target_audience"].isNull())
        {
            targetAudience_=std::make_shared<std::string>(pJson["target_audience"].asString());
        }
    }
    if(pJson.isMember("channel"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["channel"].isNull())
        {
            channel_=std::make_shared<std::string>(pJson["channel"].asString());
        }
    }
    if(pJson.isMember("subject"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["subject"].isNull())
        {
            subject_=std::make_shared<std::string>(pJson["subject"].asString());
        }
    }
    if(pJson.isMember("message_body"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["message_body"].isNull())
        {
            messageBody_=std::make_shared<std::string>(pJson["message_body"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("scheduled_time"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["scheduled_time"].isNull())
        {
            auto timeStr = pJson["scheduled_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                scheduledTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("campaign_type"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["campaign_type"].isNull())
        {
            campaignType_=std::make_shared<std::string>(pJson["campaign_type"].asString());
        }
    }
    if(pJson.isMember("reach"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["reach"].isNull())
        {
            reach_=std::make_shared<int32_t>((int32_t)pJson["reach"].asInt64());
        }
    }
    if(pJson.isMember("clicks"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["clicks"].isNull())
        {
            clicks_=std::make_shared<int32_t>((int32_t)pJson["clicks"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("html_template"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["html_template"].isNull())
        {
            htmlTemplate_=std::make_shared<std::string>(pJson["html_template"].asString());
        }
    }
}

const std::string &Campaigns::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Campaigns::getId() const noexcept
{
    return id_;
}
void Campaigns::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void Campaigns::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename Campaigns::PrimaryKeyType & Campaigns::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Campaigns::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Campaigns::getName() const noexcept
{
    return name_;
}
void Campaigns::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Campaigns::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}

const std::string &Campaigns::getValueOfDeepLink() const noexcept
{
    static const std::string defaultValue = std::string();
    if(deepLink_)
        return *deepLink_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Campaigns::getDeepLink() const noexcept
{
    return deepLink_;
}
void Campaigns::setDeepLink(const std::string &pDeepLink) noexcept
{
    deepLink_ = std::make_shared<std::string>(pDeepLink);
    dirtyFlag_[2] = true;
}
void Campaigns::setDeepLink(std::string &&pDeepLink) noexcept
{
    deepLink_ = std::make_shared<std::string>(std::move(pDeepLink));
    dirtyFlag_[2] = true;
}
void Campaigns::setDeepLinkToNull() noexcept
{
    deepLink_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Campaigns::getValueOfTargetAudience() const noexcept
{
    static const std::string defaultValue = std::string();
    if(targetAudience_)
        return *targetAudience_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Campaigns::getTargetAudience() const noexcept
{
    return targetAudience_;
}
void Campaigns::setTargetAudience(const std::string &pTargetAudience) noexcept
{
    targetAudience_ = std::make_shared<std::string>(pTargetAudience);
    dirtyFlag_[3] = true;
}
void Campaigns::setTargetAudience(std::string &&pTargetAudience) noexcept
{
    targetAudience_ = std::make_shared<std::string>(std::move(pTargetAudience));
    dirtyFlag_[3] = true;
}

const std::string &Campaigns::getValueOfChannel() const noexcept
{
    static const std::string defaultValue = std::string();
    if(channel_)
        return *channel_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Campaigns::getChannel() const noexcept
{
    return channel_;
}
void Campaigns::setChannel(const std::string &pChannel) noexcept
{
    channel_ = std::make_shared<std::string>(pChannel);
    dirtyFlag_[4] = true;
}
void Campaigns::setChannel(std::string &&pChannel) noexcept
{
    channel_ = std::make_shared<std::string>(std::move(pChannel));
    dirtyFlag_[4] = true;
}

const std::string &Campaigns::getValueOfSubject() const noexcept
{
    static const std::string defaultValue = std::string();
    if(subject_)
        return *subject_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Campaigns::getSubject() const noexcept
{
    return subject_;
}
void Campaigns::setSubject(const std::string &pSubject) noexcept
{
    subject_ = std::make_shared<std::string>(pSubject);
    dirtyFlag_[5] = true;
}
void Campaigns::setSubject(std::string &&pSubject) noexcept
{
    subject_ = std::make_shared<std::string>(std::move(pSubject));
    dirtyFlag_[5] = true;
}

const std::string &Campaigns::getValueOfMessageBody() const noexcept
{
    static const std::string defaultValue = std::string();
    if(messageBody_)
        return *messageBody_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Campaigns::getMessageBody() const noexcept
{
    return messageBody_;
}
void Campaigns::setMessageBody(const std::string &pMessageBody) noexcept
{
    messageBody_ = std::make_shared<std::string>(pMessageBody);
    dirtyFlag_[6] = true;
}
void Campaigns::setMessageBody(std::string &&pMessageBody) noexcept
{
    messageBody_ = std::make_shared<std::string>(std::move(pMessageBody));
    dirtyFlag_[6] = true;
}

const std::string &Campaigns::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Campaigns::getStatus() const noexcept
{
    return status_;
}
void Campaigns::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[7] = true;
}
void Campaigns::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[7] = true;
}

const ::trantor::Date &Campaigns::getValueOfScheduledTime() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(scheduledTime_)
        return *scheduledTime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Campaigns::getScheduledTime() const noexcept
{
    return scheduledTime_;
}
void Campaigns::setScheduledTime(const ::trantor::Date &pScheduledTime) noexcept
{
    scheduledTime_ = std::make_shared<::trantor::Date>(pScheduledTime);
    dirtyFlag_[8] = true;
}
void Campaigns::setScheduledTimeToNull() noexcept
{
    scheduledTime_.reset();
    dirtyFlag_[8] = true;
}

const std::string &Campaigns::getValueOfCampaignType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(campaignType_)
        return *campaignType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Campaigns::getCampaignType() const noexcept
{
    return campaignType_;
}
void Campaigns::setCampaignType(const std::string &pCampaignType) noexcept
{
    campaignType_ = std::make_shared<std::string>(pCampaignType);
    dirtyFlag_[9] = true;
}
void Campaigns::setCampaignType(std::string &&pCampaignType) noexcept
{
    campaignType_ = std::make_shared<std::string>(std::move(pCampaignType));
    dirtyFlag_[9] = true;
}

const int32_t &Campaigns::getValueOfReach() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(reach_)
        return *reach_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Campaigns::getReach() const noexcept
{
    return reach_;
}
void Campaigns::setReach(const int32_t &pReach) noexcept
{
    reach_ = std::make_shared<int32_t>(pReach);
    dirtyFlag_[10] = true;
}
void Campaigns::setReachToNull() noexcept
{
    reach_.reset();
    dirtyFlag_[10] = true;
}

const int32_t &Campaigns::getValueOfClicks() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(clicks_)
        return *clicks_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Campaigns::getClicks() const noexcept
{
    return clicks_;
}
void Campaigns::setClicks(const int32_t &pClicks) noexcept
{
    clicks_ = std::make_shared<int32_t>(pClicks);
    dirtyFlag_[11] = true;
}
void Campaigns::setClicksToNull() noexcept
{
    clicks_.reset();
    dirtyFlag_[11] = true;
}

const ::trantor::Date &Campaigns::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Campaigns::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Campaigns::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[12] = true;
}

const ::trantor::Date &Campaigns::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Campaigns::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void Campaigns::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[13] = true;
}
void Campaigns::setUpdatedAtToNull() noexcept
{
    updatedAt_.reset();
    dirtyFlag_[13] = true;
}

const std::string &Campaigns::getValueOfHtmlTemplate() const noexcept
{
    static const std::string defaultValue = std::string();
    if(htmlTemplate_)
        return *htmlTemplate_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Campaigns::getHtmlTemplate() const noexcept
{
    return htmlTemplate_;
}
void Campaigns::setHtmlTemplate(const std::string &pHtmlTemplate) noexcept
{
    htmlTemplate_ = std::make_shared<std::string>(pHtmlTemplate);
    dirtyFlag_[14] = true;
}
void Campaigns::setHtmlTemplate(std::string &&pHtmlTemplate) noexcept
{
    htmlTemplate_ = std::make_shared<std::string>(std::move(pHtmlTemplate));
    dirtyFlag_[14] = true;
}
void Campaigns::setHtmlTemplateToNull() noexcept
{
    htmlTemplate_.reset();
    dirtyFlag_[14] = true;
}

void Campaigns::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Campaigns::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "name",
        "deep_link",
        "target_audience",
        "channel",
        "subject",
        "message_body",
        "status",
        "scheduled_time",
        "campaign_type",
        "reach",
        "clicks",
        "created_at",
        "updated_at",
        "html_template"
    };
    return inCols;
}

void Campaigns::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDeepLink())
        {
            binder << getValueOfDeepLink();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTargetAudience())
        {
            binder << getValueOfTargetAudience();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getChannel())
        {
            binder << getValueOfChannel();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getSubject())
        {
            binder << getValueOfSubject();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMessageBody())
        {
            binder << getValueOfMessageBody();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getScheduledTime())
        {
            binder << getValueOfScheduledTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCampaignType())
        {
            binder << getValueOfCampaignType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getReach())
        {
            binder << getValueOfReach();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getClicks())
        {
            binder << getValueOfClicks();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getHtmlTemplate())
        {
            binder << getValueOfHtmlTemplate();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Campaigns::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    return ret;
}

void Campaigns::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDeepLink())
        {
            binder << getValueOfDeepLink();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTargetAudience())
        {
            binder << getValueOfTargetAudience();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getChannel())
        {
            binder << getValueOfChannel();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getSubject())
        {
            binder << getValueOfSubject();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMessageBody())
        {
            binder << getValueOfMessageBody();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getScheduledTime())
        {
            binder << getValueOfScheduledTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCampaignType())
        {
            binder << getValueOfCampaignType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getReach())
        {
            binder << getValueOfReach();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getClicks())
        {
            binder << getValueOfClicks();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getHtmlTemplate())
        {
            binder << getValueOfHtmlTemplate();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Campaigns::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getDeepLink())
    {
        ret["deep_link"]=getValueOfDeepLink();
    }
    else
    {
        ret["deep_link"]=Json::Value();
    }
    if(getTargetAudience())
    {
        ret["target_audience"]=getValueOfTargetAudience();
    }
    else
    {
        ret["target_audience"]=Json::Value();
    }
    if(getChannel())
    {
        ret["channel"]=getValueOfChannel();
    }
    else
    {
        ret["channel"]=Json::Value();
    }
    if(getSubject())
    {
        ret["subject"]=getValueOfSubject();
    }
    else
    {
        ret["subject"]=Json::Value();
    }
    if(getMessageBody())
    {
        ret["message_body"]=getValueOfMessageBody();
    }
    else
    {
        ret["message_body"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getScheduledTime())
    {
        ret["scheduled_time"]=getScheduledTime()->toDbStringLocal();
    }
    else
    {
        ret["scheduled_time"]=Json::Value();
    }
    if(getCampaignType())
    {
        ret["campaign_type"]=getValueOfCampaignType();
    }
    else
    {
        ret["campaign_type"]=Json::Value();
    }
    if(getReach())
    {
        ret["reach"]=getValueOfReach();
    }
    else
    {
        ret["reach"]=Json::Value();
    }
    if(getClicks())
    {
        ret["clicks"]=getValueOfClicks();
    }
    else
    {
        ret["clicks"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    if(getHtmlTemplate())
    {
        ret["html_template"]=getValueOfHtmlTemplate();
    }
    else
    {
        ret["html_template"]=Json::Value();
    }
    return ret;
}

std::string Campaigns::toString() const
{
    return toJson().toStyledString();
}

Json::Value Campaigns::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 15)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDeepLink())
            {
                ret[pMasqueradingVector[2]]=getValueOfDeepLink();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getTargetAudience())
            {
                ret[pMasqueradingVector[3]]=getValueOfTargetAudience();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getChannel())
            {
                ret[pMasqueradingVector[4]]=getValueOfChannel();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getSubject())
            {
                ret[pMasqueradingVector[5]]=getValueOfSubject();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getMessageBody())
            {
                ret[pMasqueradingVector[6]]=getValueOfMessageBody();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[7]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getScheduledTime())
            {
                ret[pMasqueradingVector[8]]=getScheduledTime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getCampaignType())
            {
                ret[pMasqueradingVector[9]]=getValueOfCampaignType();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getReach())
            {
                ret[pMasqueradingVector[10]]=getValueOfReach();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getClicks())
            {
                ret[pMasqueradingVector[11]]=getValueOfClicks();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[12]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[13]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getHtmlTemplate())
            {
                ret[pMasqueradingVector[14]]=getValueOfHtmlTemplate();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getDeepLink())
    {
        ret["deep_link"]=getValueOfDeepLink();
    }
    else
    {
        ret["deep_link"]=Json::Value();
    }
    if(getTargetAudience())
    {
        ret["target_audience"]=getValueOfTargetAudience();
    }
    else
    {
        ret["target_audience"]=Json::Value();
    }
    if(getChannel())
    {
        ret["channel"]=getValueOfChannel();
    }
    else
    {
        ret["channel"]=Json::Value();
    }
    if(getSubject())
    {
        ret["subject"]=getValueOfSubject();
    }
    else
    {
        ret["subject"]=Json::Value();
    }
    if(getMessageBody())
    {
        ret["message_body"]=getValueOfMessageBody();
    }
    else
    {
        ret["message_body"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getScheduledTime())
    {
        ret["scheduled_time"]=getScheduledTime()->toDbStringLocal();
    }
    else
    {
        ret["scheduled_time"]=Json::Value();
    }
    if(getCampaignType())
    {
        ret["campaign_type"]=getValueOfCampaignType();
    }
    else
    {
        ret["campaign_type"]=Json::Value();
    }
    if(getReach())
    {
        ret["reach"]=getValueOfReach();
    }
    else
    {
        ret["reach"]=Json::Value();
    }
    if(getClicks())
    {
        ret["clicks"]=getValueOfClicks();
    }
    else
    {
        ret["clicks"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    if(getHtmlTemplate())
    {
        ret["html_template"]=getValueOfHtmlTemplate();
    }
    else
    {
        ret["html_template"]=Json::Value();
    }
    return ret;
}

bool Campaigns::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("deep_link"))
    {
        if(!validJsonOfField(2, "deep_link", pJson["deep_link"], err, true))
            return false;
    }
    if(pJson.isMember("target_audience"))
    {
        if(!validJsonOfField(3, "target_audience", pJson["target_audience"], err, true))
            return false;
    }
    else
    {
        err="The target_audience column cannot be null";
        return false;
    }
    if(pJson.isMember("channel"))
    {
        if(!validJsonOfField(4, "channel", pJson["channel"], err, true))
            return false;
    }
    else
    {
        err="The channel column cannot be null";
        return false;
    }
    if(pJson.isMember("subject"))
    {
        if(!validJsonOfField(5, "subject", pJson["subject"], err, true))
            return false;
    }
    else
    {
        err="The subject column cannot be null";
        return false;
    }
    if(pJson.isMember("message_body"))
    {
        if(!validJsonOfField(6, "message_body", pJson["message_body"], err, true))
            return false;
    }
    else
    {
        err="The message_body column cannot be null";
        return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(7, "status", pJson["status"], err, true))
            return false;
    }
    else
    {
        err="The status column cannot be null";
        return false;
    }
    if(pJson.isMember("scheduled_time"))
    {
        if(!validJsonOfField(8, "scheduled_time", pJson["scheduled_time"], err, true))
            return false;
    }
    if(pJson.isMember("campaign_type"))
    {
        if(!validJsonOfField(9, "campaign_type", pJson["campaign_type"], err, true))
            return false;
    }
    else
    {
        err="The campaign_type column cannot be null";
        return false;
    }
    if(pJson.isMember("reach"))
    {
        if(!validJsonOfField(10, "reach", pJson["reach"], err, true))
            return false;
    }
    if(pJson.isMember("clicks"))
    {
        if(!validJsonOfField(11, "clicks", pJson["clicks"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(12, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(13, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    if(pJson.isMember("html_template"))
    {
        if(!validJsonOfField(14, "html_template", pJson["html_template"], err, true))
            return false;
    }
    return true;
}
bool Campaigns::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[9] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Campaigns::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("deep_link"))
    {
        if(!validJsonOfField(2, "deep_link", pJson["deep_link"], err, false))
            return false;
    }
    if(pJson.isMember("target_audience"))
    {
        if(!validJsonOfField(3, "target_audience", pJson["target_audience"], err, false))
            return false;
    }
    if(pJson.isMember("channel"))
    {
        if(!validJsonOfField(4, "channel", pJson["channel"], err, false))
            return false;
    }
    if(pJson.isMember("subject"))
    {
        if(!validJsonOfField(5, "subject", pJson["subject"], err, false))
            return false;
    }
    if(pJson.isMember("message_body"))
    {
        if(!validJsonOfField(6, "message_body", pJson["message_body"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(7, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("scheduled_time"))
    {
        if(!validJsonOfField(8, "scheduled_time", pJson["scheduled_time"], err, false))
            return false;
    }
    if(pJson.isMember("campaign_type"))
    {
        if(!validJsonOfField(9, "campaign_type", pJson["campaign_type"], err, false))
            return false;
    }
    if(pJson.isMember("reach"))
    {
        if(!validJsonOfField(10, "reach", pJson["reach"], err, false))
            return false;
    }
    if(pJson.isMember("clicks"))
    {
        if(!validJsonOfField(11, "clicks", pJson["clicks"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(12, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(13, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    if(pJson.isMember("html_template"))
    {
        if(!validJsonOfField(14, "html_template", pJson["html_template"], err, false))
            return false;
    }
    return true;
}
bool Campaigns::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Campaigns::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 350)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 350)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 150)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 150)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
