/**
 *
 *  Campaigns.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace Gnp
{

class Campaigns
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _name;
        static const std::string _deep_link;
        static const std::string _target_audience;
        static const std::string _channel;
        static const std::string _subject;
        static const std::string _message_body;
        static const std::string _status;
        static const std::string _scheduled_time;
        static const std::string _campaign_type;
        static const std::string _reach;
        static const std::string _clicks;
        static const std::string _created_at;
        static const std::string _updated_at;
        static const std::string _html_template;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Campaigns(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Campaigns(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Campaigns(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Campaigns() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;

    /**  For column deep_link  */
    ///Get the value of the column deep_link, returns the default value if the column is null
    const std::string &getValueOfDeepLink() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDeepLink() const noexcept;
    ///Set the value of the column deep_link
    void setDeepLink(const std::string &pDeepLink) noexcept;
    void setDeepLink(std::string &&pDeepLink) noexcept;
    void setDeepLinkToNull() noexcept;

    /**  For column target_audience  */
    ///Get the value of the column target_audience, returns the default value if the column is null
    const std::string &getValueOfTargetAudience() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTargetAudience() const noexcept;
    ///Set the value of the column target_audience
    void setTargetAudience(const std::string &pTargetAudience) noexcept;
    void setTargetAudience(std::string &&pTargetAudience) noexcept;

    /**  For column channel  */
    ///Get the value of the column channel, returns the default value if the column is null
    const std::string &getValueOfChannel() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getChannel() const noexcept;
    ///Set the value of the column channel
    void setChannel(const std::string &pChannel) noexcept;
    void setChannel(std::string &&pChannel) noexcept;

    /**  For column subject  */
    ///Get the value of the column subject, returns the default value if the column is null
    const std::string &getValueOfSubject() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSubject() const noexcept;
    ///Set the value of the column subject
    void setSubject(const std::string &pSubject) noexcept;
    void setSubject(std::string &&pSubject) noexcept;

    /**  For column message_body  */
    ///Get the value of the column message_body, returns the default value if the column is null
    const std::string &getValueOfMessageBody() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMessageBody() const noexcept;
    ///Set the value of the column message_body
    void setMessageBody(const std::string &pMessageBody) noexcept;
    void setMessageBody(std::string &&pMessageBody) noexcept;

    /**  For column status  */
    ///Get the value of the column status, returns the default value if the column is null
    const std::string &getValueOfStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStatus() const noexcept;
    ///Set the value of the column status
    void setStatus(const std::string &pStatus) noexcept;
    void setStatus(std::string &&pStatus) noexcept;

    /**  For column scheduled_time  */
    ///Get the value of the column scheduled_time, returns the default value if the column is null
    const ::trantor::Date &getValueOfScheduledTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getScheduledTime() const noexcept;
    ///Set the value of the column scheduled_time
    void setScheduledTime(const ::trantor::Date &pScheduledTime) noexcept;
    void setScheduledTimeToNull() noexcept;

    /**  For column campaign_type  */
    ///Get the value of the column campaign_type, returns the default value if the column is null
    const std::string &getValueOfCampaignType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCampaignType() const noexcept;
    ///Set the value of the column campaign_type
    void setCampaignType(const std::string &pCampaignType) noexcept;
    void setCampaignType(std::string &&pCampaignType) noexcept;

    /**  For column reach  */
    ///Get the value of the column reach, returns the default value if the column is null
    const int32_t &getValueOfReach() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getReach() const noexcept;
    ///Set the value of the column reach
    void setReach(const int32_t &pReach) noexcept;
    void setReachToNull() noexcept;

    /**  For column clicks  */
    ///Get the value of the column clicks, returns the default value if the column is null
    const int32_t &getValueOfClicks() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getClicks() const noexcept;
    ///Set the value of the column clicks
    void setClicks(const int32_t &pClicks) noexcept;
    void setClicksToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;

    /**  For column updated_at  */
    ///Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
    ///Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;
    void setUpdatedAtToNull() noexcept;

    /**  For column html_template  */
    ///Get the value of the column html_template, returns the default value if the column is null
    const std::string &getValueOfHtmlTemplate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getHtmlTemplate() const noexcept;
    ///Set the value of the column html_template
    void setHtmlTemplate(const std::string &pHtmlTemplate) noexcept;
    void setHtmlTemplate(std::string &&pHtmlTemplate) noexcept;
    void setHtmlTemplateToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 15;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Campaigns>;
    friend drogon::orm::BaseBuilder<Campaigns, true, true>;
    friend drogon::orm::BaseBuilder<Campaigns, true, false>;
    friend drogon::orm::BaseBuilder<Campaigns, false, true>;
    friend drogon::orm::BaseBuilder<Campaigns, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Campaigns>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> deepLink_;
    std::shared_ptr<std::string> targetAudience_;
    std::shared_ptr<std::string> channel_;
    std::shared_ptr<std::string> subject_;
    std::shared_ptr<std::string> messageBody_;
    std::shared_ptr<std::string> status_;
    std::shared_ptr<::trantor::Date> scheduledTime_;
    std::shared_ptr<std::string> campaignType_;
    std::shared_ptr<int32_t> reach_;
    std::shared_ptr<int32_t> clicks_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    std::shared_ptr<std::string> htmlTemplate_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[15]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "deep_link,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "target_audience,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "channel,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "subject,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "message_body,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "status,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "scheduled_time,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "campaign_type,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "reach,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "clicks,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[12])
        {
            needSelection=true;
        }
        if(dirtyFlag_[13])
        {
            sql += "updated_at,";
            ++parametersCount;
        }
        if(dirtyFlag_[14])
        {
            sql += "html_template,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[14])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace Gnp
} // namespace drogon_model
