/**
 *
 *  NewspaperEngagement.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "NewspaperEngagement.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Gnp;

const std::string NewspaperEngagement::Cols::_id = "\"id\"";
const std::string NewspaperEngagement::Cols::_newspaper_id = "\"newspaper_id\"";
const std::string NewspaperEngagement::Cols::_user_id = "\"user_id\"";
const std::string NewspaperEngagement::Cols::_partner_id = "\"partner_id\"";
const std::string NewspaperEngagement::Cols::_viewed_at = "\"viewed_at\"";
const std::string NewspaperEngagement::Cols::_last_viewed = "\"last_viewed\"";
const std::string NewspaperEngagement::Cols::_time_spent_seconds = "\"time_spent_seconds\"";
const std::string NewspaperEngagement::Cols::_is_completed = "\"is_completed\"";
const std::string NewspaperEngagement::Cols::_device_type = "\"device_type\"";
const std::string NewspaperEngagement::primaryKeyName = "id";
const bool NewspaperEngagement::hasPrimaryKey = true;
const std::string NewspaperEngagement::tableName = "\"newspaper_engagement\"";

const std::vector<typename NewspaperEngagement::MetaData> NewspaperEngagement::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"newspaper_id","std::string","uuid",0,0,0,1},
{"user_id","std::string","uuid",0,0,0,1},
{"partner_id","std::string","uuid",0,0,0,1},
{"viewed_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"last_viewed","::trantor::Date","timestamp with time zone",0,0,0,0},
{"time_spent_seconds","int32_t","integer",4,0,0,1},
{"is_completed","bool","boolean",1,0,0,1},
{"device_type","std::string","character varying",50,0,0,1}
};
const std::string &NewspaperEngagement::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
NewspaperEngagement::NewspaperEngagement(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["newspaper_id"].isNull())
        {
            newspaperId_=std::make_shared<std::string>(r["newspaper_id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["partner_id"].isNull())
        {
            partnerId_=std::make_shared<std::string>(r["partner_id"].as<std::string>());
        }
        if(!r["viewed_at"].isNull())
        {
            auto timeStr = r["viewed_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                viewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["last_viewed"].isNull())
        {
            auto timeStr = r["last_viewed"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastViewed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["time_spent_seconds"].isNull())
        {
            timeSpentSeconds_=std::make_shared<int32_t>(r["time_spent_seconds"].as<int32_t>());
        }
        if(!r["is_completed"].isNull())
        {
            isCompleted_=std::make_shared<bool>(r["is_completed"].as<bool>());
        }
        if(!r["device_type"].isNull())
        {
            deviceType_=std::make_shared<std::string>(r["device_type"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            newspaperId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            partnerId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                viewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastViewed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            timeSpentSeconds_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            isCompleted_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            deviceType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

NewspaperEngagement::NewspaperEngagement(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            newspaperId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            partnerId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                viewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastViewed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            timeSpentSeconds_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            isCompleted_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            deviceType_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

NewspaperEngagement::NewspaperEngagement(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("newspaper_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["newspaper_id"].isNull())
        {
            newspaperId_=std::make_shared<std::string>(pJson["newspaper_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("partner_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["partner_id"].isNull())
        {
            partnerId_=std::make_shared<std::string>(pJson["partner_id"].asString());
        }
    }
    if(pJson.isMember("viewed_at"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["viewed_at"].isNull())
        {
            auto timeStr = pJson["viewed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                viewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("last_viewed"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["last_viewed"].isNull())
        {
            auto timeStr = pJson["last_viewed"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastViewed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("time_spent_seconds"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["time_spent_seconds"].isNull())
        {
            timeSpentSeconds_=std::make_shared<int32_t>((int32_t)pJson["time_spent_seconds"].asInt64());
        }
    }
    if(pJson.isMember("is_completed"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["is_completed"].isNull())
        {
            isCompleted_=std::make_shared<bool>(pJson["is_completed"].asBool());
        }
    }
    if(pJson.isMember("device_type"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["device_type"].isNull())
        {
            deviceType_=std::make_shared<std::string>(pJson["device_type"].asString());
        }
    }
}

void NewspaperEngagement::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            newspaperId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            partnerId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                viewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastViewed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            timeSpentSeconds_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            isCompleted_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            deviceType_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

void NewspaperEngagement::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("newspaper_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["newspaper_id"].isNull())
        {
            newspaperId_=std::make_shared<std::string>(pJson["newspaper_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("partner_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["partner_id"].isNull())
        {
            partnerId_=std::make_shared<std::string>(pJson["partner_id"].asString());
        }
    }
    if(pJson.isMember("viewed_at"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["viewed_at"].isNull())
        {
            auto timeStr = pJson["viewed_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                viewedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("last_viewed"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["last_viewed"].isNull())
        {
            auto timeStr = pJson["last_viewed"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastViewed_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("time_spent_seconds"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["time_spent_seconds"].isNull())
        {
            timeSpentSeconds_=std::make_shared<int32_t>((int32_t)pJson["time_spent_seconds"].asInt64());
        }
    }
    if(pJson.isMember("is_completed"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["is_completed"].isNull())
        {
            isCompleted_=std::make_shared<bool>(pJson["is_completed"].asBool());
        }
    }
    if(pJson.isMember("device_type"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["device_type"].isNull())
        {
            deviceType_=std::make_shared<std::string>(pJson["device_type"].asString());
        }
    }
}

const std::string &NewspaperEngagement::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &NewspaperEngagement::getId() const noexcept
{
    return id_;
}
void NewspaperEngagement::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void NewspaperEngagement::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename NewspaperEngagement::PrimaryKeyType & NewspaperEngagement::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &NewspaperEngagement::getValueOfNewspaperId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(newspaperId_)
        return *newspaperId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &NewspaperEngagement::getNewspaperId() const noexcept
{
    return newspaperId_;
}
void NewspaperEngagement::setNewspaperId(const std::string &pNewspaperId) noexcept
{
    newspaperId_ = std::make_shared<std::string>(pNewspaperId);
    dirtyFlag_[1] = true;
}
void NewspaperEngagement::setNewspaperId(std::string &&pNewspaperId) noexcept
{
    newspaperId_ = std::make_shared<std::string>(std::move(pNewspaperId));
    dirtyFlag_[1] = true;
}

const std::string &NewspaperEngagement::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &NewspaperEngagement::getUserId() const noexcept
{
    return userId_;
}
void NewspaperEngagement::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[2] = true;
}
void NewspaperEngagement::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[2] = true;
}

const std::string &NewspaperEngagement::getValueOfPartnerId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(partnerId_)
        return *partnerId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &NewspaperEngagement::getPartnerId() const noexcept
{
    return partnerId_;
}
void NewspaperEngagement::setPartnerId(const std::string &pPartnerId) noexcept
{
    partnerId_ = std::make_shared<std::string>(pPartnerId);
    dirtyFlag_[3] = true;
}
void NewspaperEngagement::setPartnerId(std::string &&pPartnerId) noexcept
{
    partnerId_ = std::make_shared<std::string>(std::move(pPartnerId));
    dirtyFlag_[3] = true;
}

const ::trantor::Date &NewspaperEngagement::getValueOfViewedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(viewedAt_)
        return *viewedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &NewspaperEngagement::getViewedAt() const noexcept
{
    return viewedAt_;
}
void NewspaperEngagement::setViewedAt(const ::trantor::Date &pViewedAt) noexcept
{
    viewedAt_ = std::make_shared<::trantor::Date>(pViewedAt);
    dirtyFlag_[4] = true;
}

const ::trantor::Date &NewspaperEngagement::getValueOfLastViewed() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastViewed_)
        return *lastViewed_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &NewspaperEngagement::getLastViewed() const noexcept
{
    return lastViewed_;
}
void NewspaperEngagement::setLastViewed(const ::trantor::Date &pLastViewed) noexcept
{
    lastViewed_ = std::make_shared<::trantor::Date>(pLastViewed);
    dirtyFlag_[5] = true;
}
void NewspaperEngagement::setLastViewedToNull() noexcept
{
    lastViewed_.reset();
    dirtyFlag_[5] = true;
}

const int32_t &NewspaperEngagement::getValueOfTimeSpentSeconds() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(timeSpentSeconds_)
        return *timeSpentSeconds_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &NewspaperEngagement::getTimeSpentSeconds() const noexcept
{
    return timeSpentSeconds_;
}
void NewspaperEngagement::setTimeSpentSeconds(const int32_t &pTimeSpentSeconds) noexcept
{
    timeSpentSeconds_ = std::make_shared<int32_t>(pTimeSpentSeconds);
    dirtyFlag_[6] = true;
}

const bool &NewspaperEngagement::getValueOfIsCompleted() const noexcept
{
    static const bool defaultValue = bool();
    if(isCompleted_)
        return *isCompleted_;
    return defaultValue;
}
const std::shared_ptr<bool> &NewspaperEngagement::getIsCompleted() const noexcept
{
    return isCompleted_;
}
void NewspaperEngagement::setIsCompleted(const bool &pIsCompleted) noexcept
{
    isCompleted_ = std::make_shared<bool>(pIsCompleted);
    dirtyFlag_[7] = true;
}

const std::string &NewspaperEngagement::getValueOfDeviceType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(deviceType_)
        return *deviceType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &NewspaperEngagement::getDeviceType() const noexcept
{
    return deviceType_;
}
void NewspaperEngagement::setDeviceType(const std::string &pDeviceType) noexcept
{
    deviceType_ = std::make_shared<std::string>(pDeviceType);
    dirtyFlag_[8] = true;
}
void NewspaperEngagement::setDeviceType(std::string &&pDeviceType) noexcept
{
    deviceType_ = std::make_shared<std::string>(std::move(pDeviceType));
    dirtyFlag_[8] = true;
}

void NewspaperEngagement::updateId(const uint64_t id)
{
}

const std::vector<std::string> &NewspaperEngagement::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "newspaper_id",
        "user_id",
        "partner_id",
        "viewed_at",
        "last_viewed",
        "time_spent_seconds",
        "is_completed",
        "device_type"
    };
    return inCols;
}

void NewspaperEngagement::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getNewspaperId())
        {
            binder << getValueOfNewspaperId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getPartnerId())
        {
            binder << getValueOfPartnerId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getViewedAt())
        {
            binder << getValueOfViewedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLastViewed())
        {
            binder << getValueOfLastViewed();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getTimeSpentSeconds())
        {
            binder << getValueOfTimeSpentSeconds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIsCompleted())
        {
            binder << getValueOfIsCompleted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getDeviceType())
        {
            binder << getValueOfDeviceType();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> NewspaperEngagement::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void NewspaperEngagement::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getNewspaperId())
        {
            binder << getValueOfNewspaperId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getPartnerId())
        {
            binder << getValueOfPartnerId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getViewedAt())
        {
            binder << getValueOfViewedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLastViewed())
        {
            binder << getValueOfLastViewed();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getTimeSpentSeconds())
        {
            binder << getValueOfTimeSpentSeconds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIsCompleted())
        {
            binder << getValueOfIsCompleted();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getDeviceType())
        {
            binder << getValueOfDeviceType();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value NewspaperEngagement::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getNewspaperId())
    {
        ret["newspaper_id"]=getValueOfNewspaperId();
    }
    else
    {
        ret["newspaper_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getPartnerId())
    {
        ret["partner_id"]=getValueOfPartnerId();
    }
    else
    {
        ret["partner_id"]=Json::Value();
    }
    if(getViewedAt())
    {
        ret["viewed_at"]=getViewedAt()->toDbStringLocal();
    }
    else
    {
        ret["viewed_at"]=Json::Value();
    }
    if(getLastViewed())
    {
        ret["last_viewed"]=getLastViewed()->toDbStringLocal();
    }
    else
    {
        ret["last_viewed"]=Json::Value();
    }
    if(getTimeSpentSeconds())
    {
        ret["time_spent_seconds"]=getValueOfTimeSpentSeconds();
    }
    else
    {
        ret["time_spent_seconds"]=Json::Value();
    }
    if(getIsCompleted())
    {
        ret["is_completed"]=getValueOfIsCompleted();
    }
    else
    {
        ret["is_completed"]=Json::Value();
    }
    if(getDeviceType())
    {
        ret["device_type"]=getValueOfDeviceType();
    }
    else
    {
        ret["device_type"]=Json::Value();
    }
    return ret;
}

std::string NewspaperEngagement::toString() const
{
    return toJson().toStyledString();
}

Json::Value NewspaperEngagement::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getNewspaperId())
            {
                ret[pMasqueradingVector[1]]=getValueOfNewspaperId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[2]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getPartnerId())
            {
                ret[pMasqueradingVector[3]]=getValueOfPartnerId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getViewedAt())
            {
                ret[pMasqueradingVector[4]]=getViewedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getLastViewed())
            {
                ret[pMasqueradingVector[5]]=getLastViewed()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getTimeSpentSeconds())
            {
                ret[pMasqueradingVector[6]]=getValueOfTimeSpentSeconds();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getIsCompleted())
            {
                ret[pMasqueradingVector[7]]=getValueOfIsCompleted();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getDeviceType())
            {
                ret[pMasqueradingVector[8]]=getValueOfDeviceType();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getNewspaperId())
    {
        ret["newspaper_id"]=getValueOfNewspaperId();
    }
    else
    {
        ret["newspaper_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getPartnerId())
    {
        ret["partner_id"]=getValueOfPartnerId();
    }
    else
    {
        ret["partner_id"]=Json::Value();
    }
    if(getViewedAt())
    {
        ret["viewed_at"]=getViewedAt()->toDbStringLocal();
    }
    else
    {
        ret["viewed_at"]=Json::Value();
    }
    if(getLastViewed())
    {
        ret["last_viewed"]=getLastViewed()->toDbStringLocal();
    }
    else
    {
        ret["last_viewed"]=Json::Value();
    }
    if(getTimeSpentSeconds())
    {
        ret["time_spent_seconds"]=getValueOfTimeSpentSeconds();
    }
    else
    {
        ret["time_spent_seconds"]=Json::Value();
    }
    if(getIsCompleted())
    {
        ret["is_completed"]=getValueOfIsCompleted();
    }
    else
    {
        ret["is_completed"]=Json::Value();
    }
    if(getDeviceType())
    {
        ret["device_type"]=getValueOfDeviceType();
    }
    else
    {
        ret["device_type"]=Json::Value();
    }
    return ret;
}

bool NewspaperEngagement::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("newspaper_id"))
    {
        if(!validJsonOfField(1, "newspaper_id", pJson["newspaper_id"], err, true))
            return false;
    }
    else
    {
        err="The newspaper_id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("partner_id"))
    {
        if(!validJsonOfField(3, "partner_id", pJson["partner_id"], err, true))
            return false;
    }
    else
    {
        err="The partner_id column cannot be null";
        return false;
    }
    if(pJson.isMember("viewed_at"))
    {
        if(!validJsonOfField(4, "viewed_at", pJson["viewed_at"], err, true))
            return false;
    }
    if(pJson.isMember("last_viewed"))
    {
        if(!validJsonOfField(5, "last_viewed", pJson["last_viewed"], err, true))
            return false;
    }
    if(pJson.isMember("time_spent_seconds"))
    {
        if(!validJsonOfField(6, "time_spent_seconds", pJson["time_spent_seconds"], err, true))
            return false;
    }
    if(pJson.isMember("is_completed"))
    {
        if(!validJsonOfField(7, "is_completed", pJson["is_completed"], err, true))
            return false;
    }
    if(pJson.isMember("device_type"))
    {
        if(!validJsonOfField(8, "device_type", pJson["device_type"], err, true))
            return false;
    }
    return true;
}
bool NewspaperEngagement::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool NewspaperEngagement::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("newspaper_id"))
    {
        if(!validJsonOfField(1, "newspaper_id", pJson["newspaper_id"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("partner_id"))
    {
        if(!validJsonOfField(3, "partner_id", pJson["partner_id"], err, false))
            return false;
    }
    if(pJson.isMember("viewed_at"))
    {
        if(!validJsonOfField(4, "viewed_at", pJson["viewed_at"], err, false))
            return false;
    }
    if(pJson.isMember("last_viewed"))
    {
        if(!validJsonOfField(5, "last_viewed", pJson["last_viewed"], err, false))
            return false;
    }
    if(pJson.isMember("time_spent_seconds"))
    {
        if(!validJsonOfField(6, "time_spent_seconds", pJson["time_spent_seconds"], err, false))
            return false;
    }
    if(pJson.isMember("is_completed"))
    {
        if(!validJsonOfField(7, "is_completed", pJson["is_completed"], err, false))
            return false;
    }
    if(pJson.isMember("device_type"))
    {
        if(!validJsonOfField(8, "device_type", pJson["device_type"], err, false))
            return false;
    }
    return true;
}
bool NewspaperEngagement::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool NewspaperEngagement::validJsonOfField(size_t index,
                                           const std::string &fieldName,
                                           const Json::Value &pJson,
                                           std::string &err,
                                           bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
